export enum CaseType {
  LowerCase = "Lower Case",
  UpperCase = "Upper Case",
  ConstantCase = "Constant Case",
  CamelCase = "Camel Case",
  PascalCase = "Pascal Case",
  SnakeCase = "Snake Case",
  KebabCase = "Kebab Case",
  TitleCase = "Title Case",
  SentenceCase = "Sentence Case",
  TrainCase = "Train Case",
  DotCase = "Dot Case",
  ScreamingSnakeCase = "Screaming Snake Case",
  StudlyCaps = "Studly Caps",
}
